
export const SUBSCRIPTIONS_SUCCESS = '[SUBSCRIPTIONS] SUCCESS';
export const SUBSCRIPTIONS_FAIL = '[SUBSCRIPTIONS] FAIL';
export const SUBSCRIPTIONS_DELETE_DATA = '[SUBSCRIPTIONS] DELTE DATA';
export const SUBSCRIPTIONS_GET_SUBSCRIPTIONS = '[SUBSCRIPTIONS] GET SUBSCRIPTIONS';
export const SUBSCRIPTION_CREATE_SUBSCRIPTION = '[SUBSCRIPTION] CREATE SUBSCRIPTION';
export const SUBSCRIPTION_UPDATE_SUBSCRIPTION = '[SUBSCRIPTION] UPDATE SUBSCRIPTION';
export const SUBSCRIPTION_GET_CURRENCY = '[SUBSCRIPTION] GET CURRENCY';
export const SUBSCRIPTION_GET_PERIODS = '[SUBSCRIPTION] GET PERIODS';
