
export const TENANTS_GET_TENANTS = '[TENANTS] GET TENANTS';
export const TENANTS_GET_TENENT_BY_ID = '[TENANTS] GET TENENTS BY ID';
export const TENANTS_UPDATE_TENENTS = '[TENANTS] UPDATE TENENTS';
export const TENANTS_CREATE_TENANTS = '[TENANTS] CREATE TENANTS';
export const TENANTS_CHOOSE_SUBSCRIPTION = '[TENANTS] CHOOSE SUBSCRIPTION';
export const TENANTS_SUCCESS = '[TENANTS] SUCCESS';
export const TENANTS_FAIL = '[TENANTS] FAIL';
export const TENANTS_DELETE_DATA = '[AUTH] DELETE_DATA';
export const TENANTS_GET_ADMINS = '[TENANTS] GET ADMINS';
export const TENANTS_UPLOAD_LOGO = '[TENANTS] UPLOAD LOGO';
export const TENANTS_GET_IMAGE = '[TENANTS] GET IMAGE';
export const TENANTS_INVITE_ADMINS = '[TENANTS] INVITE ADMINS';
export const TENANTS_CREATE_DATABASE = '[TENANTS] CREATE DATABASE';
export const TENANTS_GET_COURSES = '[TENANTS] GET COURSES';
export const TENANTS_GET_STUDENTS = '[TENANTS] GET STUDENTS';
export const TENANTS_CREATE_COURSE = '[TENANTS] CREATE COURSE';
export const TENANTS_GET_PARENTS = '[TENANTS] GET PARENTS';
