
export const AUTH_SIGNIN = '[AUTH] SIGNIN';
export const AUTH_SIGNUP = '[AUTH] SIGNUP';
export const AUTH_SIGNUP_ADMIN = '[AUTH] SIGNUP ADMIN';
export const AUTH_VALIDATION_SUBDOMAIN = '[AUTH] VALIDATION_SUBDOMAIN';
export const AUTH_VALIDATION_EMAIL = '[AUTH] VALIDATION EMAIL';
export const AUTH_TOKEN = '[AUTH] TOKEN';
export const AUTH_SUCCESS = '[AUTH] SUCCESS';
export const AUTH_FAIL = '[AUTH] FAIL';
export const AUTH_DELETE_DATA = '[AUTH] DELETE_DATA';
export const AUTH_GET_SCHOOL_TYPES = '[AUTH] GET SCHOOL TYPES';
export const LOGOUT = '[AUTH] LOGOUT';
export const AUTH_VERIFY_EMAIL = '[AUTH] VERIFY EMAIL';
export const AUTH_VERIFY_INVITE_ADMIN = '[AUTH] VERIFY INVITE ADMIN';
